### ISSUE TITLE
Azure OpenAI Studio: Invalid Event Code

### ISSUE THREAD

**Issue by sivanola** [microsoft/Hack-Together-Fabric-AI#9]
Azure OpenAI Studio doesn't recognize my key. I had no issues yesterday and was able to access it and use the provides endpoint and key in Fabric notebook. Today I got this error in my notebook: Error code: 429 - {'error': {'code': 429, 'message': 'The event daily request rate of 2000 calls to has been exceeded. Requests are disabled until UTC midnight.'}}.
I couldn't have used up 2000 calls since I haven't used any today. I tried to log in to Azure OpenAI Studio and got: Invalid Event Code. The API Key provided is invalid or the event has expired. Please check the API Key and the event start and end times. 
The API Key worked yesterday.

**Comment by toolboc** [comment]
@sivanola, it is possible that there is a mistmatch between what is considered "midnight" as I believe the AOAI proxy is deployed in Asia Pacific timezone.  Have you tried requesting an updated key?

@reneenoble, do you have advice here?

**Comment by sivanola** [comment]
I've been trying for the last 9 hours. And I hadn't made even close to 2000 calls yesterday. I haven't tried requesting another key.

**Comment by reneenoble** [comment]
@sivanola Thanks for logging this issue. Firstly, would you be able to try going back to the [registration page](https://polite-ground-030dc3103.4.azurestaticapps.net/event/1hy6-u87f/?WT.mc_id=academic-120916-reneenoble) and making sure you are still logged in. There have been a couple of new released on the server that might have meant you got logged out. 

Once you know you're logged in can you try the key in the playground (don't forget to select a model in the right hand panel). Would be worth checking if this is the same key that you had before or if it is new. 

I'll be interested to know if the playground works for a small message. We do have a tokens per minute limit, so if your code is sending a very big payload that could be causing the issue as well (which is separate to the 2000 calls a day limit). 

@gloveboxes @aaronpowell any other thoughts?

**Comment by gloveboxes** [comment]
@sivanola, are you still having issues?

**Comment by sivanola** [comment]
The issue resolved by itself. It still happens every now and then. It's not related to tokens per minute or daily quota.
